# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c6e5b5b424dac5d713de9a5e531da76f6bf74d4b8b8ff104b6511940b938b1a7da1b839df158cd2799044dd7238970d3a45bf64170cee95bbddafed1397cdbe
  european_central_bank_url: http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
test:
  secret_key_base: 25456a6c941054142eb78b16260c8341cc804eb25b9f4d15a8329bc82c87e061ee36c7924a46d2fb997c520ddae3ba6472c10efa7bfaf55733088eaa8867797b
  european_central_bank_url: http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  european_central_bank_url: http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
